/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false packages/jelly-party-server/src/worker-configuration.d.ts` (hash: abb5875028dde7a57ccad954ade5c963)
interface __BaseEnv_Env {
	PARTY_CREATION_RATE_LIMITER: RateLimit;
	PARTY_CONNECTION_RATE_LIMITER: RateLimit;
	MAX_PARTIES_PER_MONTH: "1000000";
	PARTY: DurableObjectNamespace<import("./main").Party>;
	PARTY_QUOTA: DurableObjectNamespace<import("./main").PartyQuota>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
		durableNamespaces: "Party" | "PartyQuota";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_PARTIES_PER_MONTH">> {}
}
