/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false packages/jelly-party-server/src/worker-configuration.d.ts` (hash: 45c980ed915c3de5e1cd64083786e677)
interface __BaseEnv_Env {
	PARTY: DurableObjectNamespace<import("./main").Party>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
		durableNamespaces: "Party";
	}
	interface StagingEnv {
		PARTY: DurableObjectNamespace<import("./main").Party>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
