/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false packages/jelly-party-server/src/worker-configuration.d.ts` (hash: 2188e04420870445d65d1707eca24d20)
interface __BaseEnv_Env {
	PARTY: DurableObjectNamespace<import("./main").Party>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
		durableNamespaces: "Party";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
